const promptsEnum = {
  welcome: `Welcome to "The Forbidden Forest," a text-based RPG game set in a magical realm full of danger, adventure, and mystery. In this game, you play as a brave adventurer who must navigate the treacherous forest and uncover its secrets. Your ultimate goal is to reach the heart of the forest and discover the truth behind its dark power.\n
  The story begins as you find yourself lost in the Forbidden Forest. You have heard rumors of its dangers and the mysterious creatures that inhabit it, but you never thought you would find yourself here. As you wander deeper into the forest, you realize that something is not right. The trees are twisted and gnarled, the air is thick with magic, and the creatures that roam the forest are unlike anything you have ever seen.\n
  As you explore, you discover that the forest is home to powerful magic, both light and dark. The inhabitants of the forest, including witches, wizards, and other mystical beings, are at odds with each other, and you must choose which side to align with. Will you help the light magic users defend the forest from the dark magic users who seek to control it? Or will you side with the dark magic users, who promise you great power and reward for your allegiance?\n
  As you progress through the game, you will encounter various challenges, puzzles, and battles. You will have to use your wits and your strength to overcome these obstacles and emerge victorious. You will also have to make choices that will affect the outcome of the game, and determine your ultimate fate in the Forbidden Forest.\n
  The heart of the forest holds the greatest challenge of all. Here, you will face the ultimate enemy, the one who seeks to control the power of the forest for their own dark purposes. It is up to you to defeat this enemy and restore balance to the magical realm.\n
  Will you be able to overcome the challenges of the Forbidden Forest and emerge victorious? Only time will tell. Good luck, adventurer. Your destiny awaits.`,
  firstRoom: `As you enter the first room of the Forbidden Forest, you find yourself in a dimly lit chamber. The walls are made of rough-hewn stone, and torches flicker on the walls, casting eerie shadows across the room. You can hear the sound of dripping water in the distance, and the air is damp and musty.\n
  In the center of the room, you see a large stone pedestal, on which rests a glowing crystal. The crystal emits a soft blue light, illuminating the room and casting a mysterious glow on the walls.\n
  As you approach the pedestal, you notice that there are several inscriptions etched into the stone around it. The inscriptions are written in an ancient language that you cannot read, but they seem to be of great significance. You can sense that there is some kind of power emanating from the crystal, and you feel drawn to it.\n
  What will you do? Will you approach the crystal and try to harness its power? Or will you explore the rest of the room and see if there are any other clues or items that might be of use to you? The choice is yours.`,
  approach: `As you approach the glowing crystal, you feel a strange energy coursing through your body. The light from the crystal seems to be pulsing in time with your heartbeat, and you feel as though it is drawing you closer.\n
  As you reach out to touch the crystal, you feel a sudden surge of power rush through you. You can feel the magic of the crystal flowing into you, and you are filled with a sense of strength and vitality.\n
  But as the power fades, you begin to feel a sense of unease. You can sense that there is something dark and dangerous lurking in the depths of the forest, and you know that you must be careful if you are to survive.\n
  As you step back from the pedestal, you notice that the inscriptions on the stone are glowing faintly. You cannot decipher their meaning, but you sense that they may hold the key to unlocking the secrets of the Forbidden Forest.\n
  What will you do next? Will you continue to explore the room, or will you venture further into the forest to uncover its mysteries? The choice is yours.`,
  continue: `You decide to explore the rest of the room before approaching the crystal. As you scan the walls and floor, you notice that there are several loose stones scattered around the room. You also spot a small alcove in the corner of the room, which appears to be hiding something.\n
  You begin to examine the loose stones, trying to determine if they hold any significance. As you pick up one of the stones, you notice that there is a small symbol etched into its surface. You cannot decipher the symbol's meaning, but you sense that it may be important.\n
  You then turn your attention to the alcove in the corner of the room. As you approach, you see that there is a small chest hidden inside. You cautiously open the chest and discover a small pouch containing a handful of gold coins.\n
  As you inspect the rest of the room, you notice that there are several inscriptions etched into the stone walls. Although you cannot understand their meaning, you get the sense that they hold great significance.\n
  What will you do now? Will you continue to explore the room, or will you venture deeper into the forest to uncover its secrets? The choice is yours.`
};

module.exports = { promptsEnum };